stages:
  - build
  - test
#  - push

variables:
  NAME: web

Build container:
  stage: build
  tags:
    - docker-runner
  image: docker:20.10.18
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$NAME:$CI_COMMIT_SHORT_SHA .


Test container:
  stage: test
  tags:
    - shell-runner
  script:
    - docker --version
    - docker run -it --rm -p 8000:8000 $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$NAME:$CI_COMMIT_SHORT_SHA python manage runserver 0.0.0.0:8000
    - curl -o - -I http://localhost:8000





# Test container:
#   stage: test
#   tags:
#     - docker-runner
#   image: docker:20.10.18
#   services:
#     - docker:dind
#   script:
#     



# Push to registry:
#   stage: push
#   tags:
#     - docker-runner
#   image: docker:20.10.18
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     - docker push $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$NAME:$CI_COMMIT_SHORT_SHA
