version: '3.9'
services:
  web:
    build: .
    command: /bin/bash -c "gunicorn demo.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - ./database/:/database/
      - ./static_in_env/:/app/static_in_env/
      - ./media_root/:/app/media_root/
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./static_in_env/:/staticfiles/
      - ./media_root/:/media/
    depends_on:
      - web
