version: '3.9'
services:
  web:
    image: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$NAME:$CI_COMMIT_SHORT_SHA
    #image: gitlab.corp.local:5050/alexander/django_cicd/web:08e8ab50
    command: /bin/bash -c "gunicorn demo.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    volumes:
      - /home/deployer/database/:/app/database/
      - /home/deployer/staticfiles/:/app/static_in_env/
      - /home/deployer/media/:/media_root/
  nginx:
    image: $CI_REGISTRY/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME/$WEBSERVER:$CI_COMMIT_SHORT_SHA
    #image: gitlab.corp.local:5050/alexander/django_cicd/nginx:08e8ab50
    ports:
      - 80:80
    volumes:
      - /home/deployer/staticfiles/:/staticfiles/
      - /home/deployer/media/:/media/
    depends_on:
      - web
